plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.espserial'
version = '0.1.0'

repositories {
  maven { url 'https://jitpack.io' }
}

android {
  namespace "expo.modules.espserial"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.github.mik3y:usb-serial-for-android:3.11.0'
}
